import { Megaphone } from "lucide-react";
import { requireAdminPageContext } from "@/lib/admin/auth";
import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { BloggerReviewsAdminClient } from "./blogger-reviews-client";

export default async function AdminBloggerReviewsPage() {
  await requireAdminPageContext();
  return (
    <>
      <AdminPageHeader
        title="Blogger reviews"
        description="Edit, re-summarize, publish, or delete the 博主点评 cards shown on each shoe's comments slide. Generated by the local ingest + summarize scripts."
        icon={Megaphone}
      />
      <BloggerReviewsAdminClient />
    </>
  );
}
