-- Stores the current weekly personalized digest per user (one row each,
-- regenerated by the weekly cron). Read by the in-app /for-you page and, later,
-- by the push sender.

create table if not exists weekly_digests (
  user_id uuid primary key references profiles(id) on delete cascade,
  generated_at timestamptz not null default now(),
  compare_shoes jsonb not null default '[]',     -- [{ id, name, slug }]
  recommendations jsonb not null default '[]',   -- [{ id, name, slug, stars, reason }]
  push_title text,
  push_body text,
  deep_link text
);

alter table weekly_digests enable row level security;

-- Users read their own digest; the cron writes via the service role (bypasses RLS).
create policy "Own digest read" on weekly_digests
  for select to authenticated using (auth.uid() = user_id);
